# Generated by Django 4.2.2 on 2023-06-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile_pic',
            new_name='thumbnail',
        ),
    ]
