# Generated by Django 4.2.2 on 2023-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_video_text_image_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
