# Generated by Django 4.2.2 on 2023-06-09 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0003_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['object_id', 'pk']},
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='formation_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
