# Generated by Django 4.2.2 on 2023-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_content_options_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=600, upload_to='Img/course_files'),
        ),
    ]
