# Generated by Django 4.2.2 on 2023-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_alter_course_thumbnail_url_result_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
