# Generated by Django 4.2.2 on 2023-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_course_total_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id']},
        ),
    ]
